<?php
//1.    ctype_alnum(var); Value must be A-Z and int (int in string => "10" Not => 10) == true value is numeric . else = value isn't numeric false
//2.    ctype_alpha(var); just will accpet A-Z
//3.    ctype_cntrl(var); just will accept controller charecters => \n - \t and ...
//4.    ctype_digit(var); just will accept int not decimal, float or ...
//5.    ctype_graph(var); just will accept sth that could be dump/print on page
//6.    ctype_print(var); its like ctype_graph() but it doesn't have problem with white space in value
//7.    ctype_lower(var); just will accept lowercase charecters a-z
//8.    ctype_punct(var); just will accept ! @ # ) * $ ) and ...
//9.    ctype_space(var); just will accept charecters that they can make white space. like => \n or ...
//10.   ctype_upper(var); just will accept uppercase charecters A-Z
//11.   ctype_xdigit(var); just will accept hex code
